---
title: "Knowledge Gaps and Research Priorities"
subtitle: ""
title-block-banner: "#adb5bd"
title-block-banner-color: white
---

## Progress since NBA 2018

NBA 2018 attempted a comprehensive summary of knowledge gaps causing limitations to the NBA, which resulted in a long list of research, monitoring and data management priorities for all components of the NBA. This table summarises the progress that has been made, highlighting the gaps that still remain:

|  |  |
|----|----|
| **Priority from NBA 2018** | **Summary of progress since NBA 2018** |
| Biotic and abiotic monitoring | Long-term, focused, site-based monitoring of biodiversity and pressures on biodiversity, as well as the monitoring of specific species at larger scales (e.g., harvested species, invasive alien species, etc.) remain insufficient. While there are some long-term site-based and species monitoring programmes, many suffer from a lack of resources. Abiotic information (e.g., water turbidity, sediments, temperature, pesticide load, microplastics, etc.) is crucial for mapping ecosystems and their condition, and much of this information is not collected and/or poorly understood in terms of their impacts on ecological condition. Further investment in strategic monitoring and data systems is needed. See also key message C2. |
| Incorporating genetic diversity measures | There is ongoing progress on emerging genetic diversity indicators (see the genetic diversity indicators section), however the species and taxonomic groups included in these indicators are a small sample and coverage needs to be expanded. |
| Taxonomic coverage and taxonomists | While some progress has been made through projects that focus on foundational biodiversity information for certain taxonomic groups (e.g., the SeaMap and REFRESH projects have addressed some gaps in marine and freshwater invertebrates respectively), many invertebrate taxonomic groups suffer from a lack of information (descriptions, life history, taxonomic review, etc.), expertise, and diminishing capacity in collections facilities. Across many other taxonomic groups there is still a need to revitalise taxonomic efforts for species descriptions and to build capacity amongst taxonomists. |
| Improved classification of ecosystem types and an integrated ecosystem classification system | Each realm continues to make steady progress in ecosystem classification and mapping, with regular cycles of updates and version releases. The first edition of the [South African National Ecosystem Classification System Handbook](http://hdl.handle.net/20.500.12143/7150) was published by SANBI in 2021. The mapping and classification of South Africa’s aquatic systems, especially riparian areas, wetlands and the deep sea, remain a challenge due to limited foundational data and ground-truthing. |
| Measuring and mapping ecological condition and pressures data | Ecological condition data underpins our ability to assess the risk of collapse of ecosystems. Since the NBA 2018, new data on invasive alien plant species density and distribution have enhanced our RLE assessments on land, and focussed research on rangeland condition is starting to bear fruit – though comprehensive data sets will only be finalised in 2026-2027. Climate change models have improved and inform species assessments, and will be used in future ecosystem assessments. Marine pressure data are outdated and limits reliable condition assessment in the marine realm. Recently, extensive ecological modelling work has resulted in comprehensive wetland health data. The automated WET-Health 2.0 links seamlessly to the widely used field assessment methodology, and allows broad assumptions to be drawn on which driving component (hydrology, water quality, vegetation or geomorphology) is most impacted per wetland, each wetland buffer and the wetland’s receiving catchment. More work is required on microplastics, pesticides and other pollutants in order for such data to be useful in ecosystem and species assessments |
| Mapping and assessing ecological infrastructure | Mapping has advanced for water-related ecological infrastructure (Strategic Water Source Areas, wetlands and rivers) within two large demonstration catchments. Advances have also been made in the terrestrial and marine realms, though much work remains. |
| Indicators linking biodiversity and human wellbeing | NBA 2018 showcased several facts and statistics via the [Compendium of Benefits of Biodiversity](http://hdl.handle.net/20.500.12143/8052). Unfortunately few of these have been updated. The Multidimensional Biodiversity Index Project (2022-2024) piloted a composite indicator for South Africa. It consists of two sub-indices, the Biodiversity Index (BI) that focuses on the state of biodiversity; and the Biodiversity Contributions to People Index (BCPI) that assesses how biodiversity supports human wellbeing through regulation, material provision and non-material benefits. Funding is needed for future steps for the MBI, including further development of BCPI indicators. |
| Monitoring effectiveness of interventions and responses | There are good examples of indicators being developed to monitor the effectiveness of actions and responses to pressures on biodiversity (e.g., [*The status of biological invasions and their management in South Africa*](https://iasreport.sanbi.org.za/) is a regular report using various important indicators; and case studies have evaluated the effectiveness of maps of Critical Biodiversity Areas and threatened ecosystem regulations in certain biomes/provinces) (**von Standen et al., 2022**). More work is needed, ideally using counter-factual impact evaluation methods, to monitor the impact of interventions, especially restoration/recovery interventions. See also key message B5. |
| Data management and sharing | SANBI has made some progress on a national biodiversity information system ([Biodiversity Advisor](https://biodiversityadvisor.sanbi.org/))) which aims to enhance South Africa’s open access approach to biodiversity information, through allowing users to search seamlessly across multiple sources of information. SANBI has also undertaken substantial capacity development for the skills needed to streamline and automate indicator calculation and produce dashboards. The upcoming National Biodiversity Monitoring System aims to provide dashboards of key biodiversity indicators, underpinned by transparent workflows and databases. The move to an online NBA enables more regular updating of certain NBA indicators. |

## Additional knowledge gaps and research priorities

Collaboration from multiple institutions and individuals is a key tenet of the NBA. Government departments and entities, academic institutions, non-profit organisations and civil society are encouraged to become involved in any of the priorities mentioned above or in this list of additional knowledge gaps and research priorities:

-   Improving [South Africa’s Key Biodiversity Areas (KBA)](https://www.sanbi.org/biodiversity/building-knowledge/biodiversity-monitoring-assessment/key-biodiversity-areas-in-south-africa/) network, especially in aquatic and coastal environments, and the strategic utilisation of the KBA data for reporting, prioritisation, fundraising and more.

-   Enhancing efforts for tools that assist in mapping and assessing biodiversity, such as upscaling DNA barcoding, expanding South Africa’s biobanks, and advancing the use of environmental DNA (eDNA).

-   Improving the capacity to do more assessments at more regular time intervals – including the data science capabilities that are required for database design and workflow management.

-   Improving the integration of social and natural sciences, particularly for the expansion and updating of facts and statistics about the benefits of biodiversity, and for further incorporation of indigenous and local knowledge into biodiversity mapping, assessments, prioritisation and planning processes.
